name: ai-videoclipper
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pyqt=6.7.*
  - pyqt-multimedia
  - ffmpeg
  - libmagic
  - pip
  - pip:
      - clipsai
      - numpy
      - pandas
