name: ai-videoclipper
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pyqt=6.7.*
  - ffmpeg
  - libmagic
  - pip
  - pip:
      - PyQt6[multimedia]
      - clipsai
      - numpy
      - pandas
